export enum ContactImportErrorType {
  MISSING_PHONE = 'MISSING_PHONE',
  INVALID_PHONE = 'INVALID_PHONE',
  DUPLICATE = 'DUPLICATE',
  EXISTS = 'EXISTS',
  MISSING_REQUIRED = 'MISSING_REQUIRED',
  OTHER = 'OTHER',
}
