export enum ContactBulkAction {
  ADD_TO_GROUP = 'ADD_TO_GROUP',
  REMOVE_FROM_GROUP = 'REMOVE_FROM_GROUP',
  ADD_TAG = 'ADD_TAG',
  REMOVE_TAG = 'REMOVE_TAG',
  ACTIVATE = 'ACTIVATE',
  DEACTIVATE = 'DEACTIVATE',
  BLACKLIST = 'BLACKLIST',
  SMS_BLOCK = 'SMS_BLOCK',
  DELETE = 'DELETE',
  EXPORT = 'EXPORT',
}
