export enum CredentialType {
  SMS_PASSWORD = 'SMS_PASSWORD',
  SMS_API_KEY = 'SMS_API_KEY',
  IYS_API_KEY = 'IYS_API_KEY',
  SERVICE_API_KEY = 'SERVICE_API_KEY',
  FILE_PASSWORD = 'FILE_PASSWORD',
}
