export enum CustomerType {
  PRIVATE_SECTOR = 'PRIVATE_SECTOR',
  PUBLIC = 'PUBLIC',
  NGO_CHAMBER = 'NGO_CHAMBER',
  DEALER_PARTNER = 'DEALER_PARTNER',
  INDIVIDUAL_BUSINESS = 'INDIVIDUAL_BUSINESS',
}
