export enum InboxEventType {
  ORIGINATOR_REQUESTED = 'ORIGINATOR_REQUESTED',
  ORIGINATOR_APPROVED = 'ORIGINATOR_APPROVED',
  ORIGINATOR_PASSIVATED = 'ORIGINATOR_PASSIVATED',
  ORIGINATOR_BANNED = 'ORIGINATOR_BANNED',
}
