export enum SmsExcludeReason {
  INVALID_MOBILE = 'INVALID_MOBILE',
  MISSING_MOBILE = 'MISSING_MOBILE',
  DUPLICATE_MOBILE = 'DUPLICATE_MOBILE',
  USER_REMOVED = 'USER_REMOVED',
  BLACKLIST = 'BLACKLIST',
  SMS_BLOCKED = 'SMS_BLOCKED',
  PASSIVE = 'PASSIVE',
  NO_CONSENT = 'NO_CONSENT',
  ORIGINATOR_BLOCKED = 'ORIGINATOR_BLOCKED',
  CANCELLED = 'CANCELLED',
}
