export enum SmsRecipientStatus {
  INCLUDED = 'INCLUDED',
  EXCLUDED = 'EXCLUDED',
  INVALID = 'INVALID',
  DUPLICATE = 'DUPLICATE',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  ACCEPTED = 'ACCEPTED',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED',
}
