export enum SmsCampaignSourceType {
  CONTACT_GROUP = 'CONTACT_GROUP',
  CONTACT_PICK = 'CONTACT_PICK',
  CONTACT_BOOK = 'CONTACT_BOOK',
  MANUAL = 'MANUAL',
  FILE = 'FILE',
  CUSTOMER_CATEGORY = 'CUSTOMER_CATEGORY',
  TAG = 'TAG',
}
